name: Model Training CICD
permissions:
  id-token: write
  contents: write
 
on:
  - push

jobs:
  run:
    runs-on:
      - ubuntu-latest
   
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train_model.py

          echo "RF and LR Model Score" >report.md
          cat scores.txt >> report.md
         
          echo "Confusion Matrix & Feature Importance">report1.md
          echo '|[](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '|[](./FeatureImportance.png "FeatureImportance")' >> report1.md
     
          cat report.md report1.md >> combined_file.md
          cml comment create combined_file.md

Add class comment…


Announcement: 'name: CI/CD Pipeline for ML Model on:…'
kodi datascientist
Created 16:5616:56
name: CI/CD Pipeline for ML Model

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v3

      # Step 2: Download Iris dataset (if not in the repo)
      - name: Download Iris Dataset from UCI
        run: |
          curl -o iris.csv https://raw.githubusercontent.com/kodigitaccount/cicd_iris/refs/heads/main/iris.csv

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 5: Train the model
      - name: Train Model
        run: |
          python mlcode.py
